// ignore_for_file: lines_longer_than_80_chars

import "package:test/test.dart";
import "package:think_simple/core/extensions/string_difference_comparison.dart";

//!!!! WARNING - tests were generated by ChatGPT. I've noticed they are incorrect

void main() {
  group("String Comparison Tests", () {
    test("Identical Strings", () {
      expect(
        ("hello world".isNoticablyDifferentThan("hello world")),
        false,
      );
    });

    test("Completely Different Strings", () {
      expect(("abcdefg".isNoticablyDifferentThan("1234567")), false);
    });

    test("One Character Difference", () {
      expect(
        ("hello world".isNoticablyDifferentThan("hello worle")),
        false,
      );
    });

    test("16 Character Difference", () {
      expect(
        ("abcdefghijklmnopqrstuvwxyz"
            .isNoticablyDifferentThan("zyxwvutsrqponmlkjihgfedcba")),
        true,
      );
    });

    test("17 Character Difference", () {
      expect(
        "hello world".isNoticablyDifferentThan("goodbye universe!"),
        true,
      );
    });

    test("More than 16 Character Difference with Same Length", () {
      expect("abcdefghijk".isNoticablyDifferentThan("1234567890"), false);
    });

    test("Both Strings Empty", () {
      expect("".isNoticablyDifferentThan(""), false);
    });

    test("One String Empty", () {
      expect("hello".isNoticablyDifferentThan(""), false);
    });

    test("Large Strings with More than 16 Character Difference", () {
      expect(
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
            .isNoticablyDifferentThan(
          "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        ),
        true,
      );
    });

    test("Large Strings with Less than or Equal to 16 Character Difference",
        () {
      expect(
        "This is a long string with some differences.".isNoticablyDifferentThan(
          "This is a long string with some differences!",
        ),
        false,
      );
    });
  });
}
