name: think_simple
description: "An app for writing down your thoughts. Fast and easily."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  provider: ^6.1.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.24.9
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  # assets:
#    - "assets/images/"

  # fonts:
#    - family: SourceSans
#      fonts:
#        - asset: fonts/SourceSans3-VariableFont_wght.ttf

